/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EmbeddingItem,
    EmbeddingItemFromJSON,
    EmbeddingItemFromJSONTyped,
    EmbeddingItemToJSON,
} from './';

/**
 * EmbeddingsResponse
 * @export
 * @interface EmbeddingsResponse
 */
export interface EmbeddingsResponse {
    /**
     * Loaded，Embeddings loaded for the current model
     * @type {{ [key: string]: EmbeddingItem; }}
     * @memberof EmbeddingsResponse
     */
    loaded: { [key: string]: EmbeddingItem; };
    /**
     * Skipped，Embeddings skipped for the current model (likely due to architecture incompatibility)
     * @type {{ [key: string]: EmbeddingItem; }}
     * @memberof EmbeddingsResponse
     */
    skipped: { [key: string]: EmbeddingItem; };
}

export function EmbeddingsResponseFromJSON(json: any): EmbeddingsResponse {
    return EmbeddingsResponseFromJSONTyped(json, false);
}

export function EmbeddingsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmbeddingsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'loaded': (mapValues(json['loaded'], EmbeddingItemFromJSON)),
        'skipped': (mapValues(json['skipped'], EmbeddingItemFromJSON)),
    };
}

export function EmbeddingsResponseToJSON(value?: EmbeddingsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'loaded': (mapValues(value.loaded, EmbeddingItemToJSON)),
        'skipped': (mapValues(value.skipped, EmbeddingItemToJSON)),
    };
}


