/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * ExtensionItem
 * @export
 * @interface ExtensionItem
 */
export interface ExtensionItem {
    /**
     * Name，Extension name
     * @type {string}
     * @memberof ExtensionItem
     */
    name: string;
    /**
     * Remote，Extension Repository URL
     * @type {string}
     * @memberof ExtensionItem
     */
    remote: string;
    /**
     * Branch，Extension Repository Branch
     * @type {string}
     * @memberof ExtensionItem
     */
    branch: string;
    /**
     * Commit Hash，Extension Repository Commit Hash
     * @type {string}
     * @memberof ExtensionItem
     */
    commitHash: string;
    /**
     * Version，Extension Version
     * @type {string}
     * @memberof ExtensionItem
     */
    version: string;
    /**
     * Commit Date，Extension Repository Commit Date
     * @type {string}
     * @memberof ExtensionItem
     */
    commitDate: string;
    /**
     * Enabled，Flag specifying whether this extension is enabled
     * @type {boolean}
     * @memberof ExtensionItem
     */
    enabled: boolean;
}

export function ExtensionItemFromJSON(json: any): ExtensionItem {
    return ExtensionItemFromJSONTyped(json, false);
}

export function ExtensionItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtensionItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'remote': json['remote'],
        'branch': json['branch'],
        'commitHash': json['commit_hash'],
        'version': json['version'],
        'commitDate': json['commit_date'],
        'enabled': json['enabled'],
    };
}

export function ExtensionItemToJSON(value?: ExtensionItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'remote': value.remote,
        'branch': value.branch,
        'commit_hash': value.commitHash,
        'version': value.version,
        'commit_date': value.commitDate,
        'enabled': value.enabled,
    };
}


