/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * PNGInfoRequest
 * @export
 * @interface PngInfoRequest
 */
export interface PngInfoRequest {
    /**
     * Image，The base64 encoded PNG image
     * @type {string}
     * @memberof PngInfoRequest
     */
    image: string;
}

export function PngInfoRequestFromJSON(json: any): PngInfoRequest {
    return PngInfoRequestFromJSONTyped(json, false);
}

export function PngInfoRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PngInfoRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function PngInfoRequestToJSON(value?: PngInfoRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'image': value.image,
    };
}


