/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SamplerItem
 * @export
 * @interface SamplerItem
 */
export interface SamplerItem {
    /**
     * Name
     * @type {string}
     * @memberof SamplerItem
     */
    name: string;
    /**
     * Aliases
     * @type {Array<string>}
     * @memberof SamplerItem
     */
    aliases: Array<string>;
    /**
     * Options
     * @type {{ [key: string]: string; }}
     * @memberof SamplerItem
     */
    options: { [key: string]: string; };
}

export function SamplerItemFromJSON(json: any): SamplerItem {
    return SamplerItemFromJSONTyped(json, false);
}

export function SamplerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SamplerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'aliases': json['aliases'],
        'options': json['options'],
    };
}

export function SamplerItemToJSON(value?: SamplerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'aliases': value.aliases,
        'options': value.options,
    };
}


