/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SchedulerItem
 * @export
 * @interface SchedulerItem
 */
export interface SchedulerItem {
    /**
     * Name
     * @type {string}
     * @memberof SchedulerItem
     */
    name: string;
    /**
     * Label
     * @type {string}
     * @memberof SchedulerItem
     */
    label: string;
    /**
     * Aliases
     * @type {Array<string>}
     * @memberof SchedulerItem
     */
    aliases?: Array<string>;
    /**
     * Default Rho
     * @type {number}
     * @memberof SchedulerItem
     */
    defaultRho?: number;
    /**
     * Needs Inner Model
     * @type {boolean}
     * @memberof SchedulerItem
     */
    needInnerModel?: boolean;
}

export function SchedulerItemFromJSON(json: any): SchedulerItem {
    return SchedulerItemFromJSONTyped(json, false);
}

export function SchedulerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchedulerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'label': json['label'],
        'aliases': !exists(json, 'aliases') ? undefined : json['aliases'],
        'defaultRho': !exists(json, 'default_rho') ? undefined : json['default_rho'],
        'needInnerModel': !exists(json, 'need_inner_model') ? undefined : json['need_inner_model'],
    };
}

export function SchedulerItemToJSON(value?: SchedulerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'label': value.label,
        'aliases': value.aliases,
        'default_rho': value.defaultRho,
        'need_inner_model': value.needInnerModel,
    };
}


