/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * SDModelItem
 * @export
 * @interface SdModelItem
 */
export interface SdModelItem {
    /**
     * Title
     * @type {string}
     * @memberof SdModelItem
     */
    title: string;
    /**
     * Model Name
     * @type {string}
     * @memberof SdModelItem
     */
    modelName: string;
    /**
     * Short hash
     * @type {string}
     * @memberof SdModelItem
     */
    hash?: string;
    /**
     * sha256 hash
     * @type {string}
     * @memberof SdModelItem
     */
    sha256?: string;
    /**
     * Filename
     * @type {string}
     * @memberof SdModelItem
     */
    filename: string;
    /**
     * Config file
     * @type {string}
     * @memberof SdModelItem
     */
    config?: string;
}

export function SdModelItemFromJSON(json: any): SdModelItem {
    return SdModelItemFromJSONTyped(json, false);
}

export function SdModelItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): SdModelItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'title': json['title'],
        'modelName': json['model_name'],
        'hash': !exists(json, 'hash') ? undefined : json['hash'],
        'sha256': !exists(json, 'sha256') ? undefined : json['sha256'],
        'filename': json['filename'],
        'config': !exists(json, 'config') ? undefined : json['config'],
    };
}

export function SdModelItemToJSON(value?: SdModelItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'title': value.title,
        'model_name': value.modelName,
        'hash': value.hash,
        'sha256': value.sha256,
        'filename': value.filename,
        'config': value.config,
    };
}


