/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * StableDiffusionProcessingTxt2Img
 * @export
 * @interface StableDiffusionProcessingTxt2Img
 */
export interface StableDiffusionProcessingTxt2Img {
    /**
     * Prompt
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    prompt?: string;
    /**
     * Negative Prompt
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    negativePrompt?: string;
    /**
     * Styles
     * @type {Array<string>}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    styles?: Array<string>;
    /**
     * Seed
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seed?: number;
    /**
     * Subseed
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    subseed?: number;
    /**
     * Subseed Strength
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    subseedStrength?: number;
    /**
     * Seed Resize From H
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seedResizeFromH?: number;
    /**
     * Seed Resize From W
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    seedResizeFromW?: number;
    /**
     * Sampler Name
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    samplerName?: string;
    /**
     * Scheduler
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    scheduler?: string;
    /**
     * Batch Size
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    batchSize?: number;
    /**
     * N Iter
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    nIter?: number;
    /**
     * Steps
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    steps?: number;
    /**
     * Cfg Scale
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    cfgScale?: number;
    /**
     * Width
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    width?: number;
    /**
     * Height
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    height?: number;
    /**
     * Restore Faces
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    restoreFaces?: boolean;
    /**
     * Tiling
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    tiling?: boolean;
    /**
     * Do Not Save Samples
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    doNotSaveSamples?: boolean;
    /**
     * Do Not Save Grid
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    doNotSaveGrid?: boolean;
    /**
     * Eta
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    eta?: number;
    /**
     * Denoising Strength
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    denoisingStrength?: number;
    /**
     * S Min Uncond
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sMinUncond?: number;
    /**
     * S Churn
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sChurn?: number;
    /**
     * S Tmax
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sTmax?: number;
    /**
     * S Tmin
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sTmin?: number;
    /**
     * S Noise
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sNoise?: number;
    /**
     * Override Settings
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    overrideSettings?: object;
    /**
     * Override Settings Restore Afterwards
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    overrideSettingsRestoreAfterwards?: boolean;
    /**
     * Refiner Checkpoint
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    refinerCheckpoint?: string;
    /**
     * Refiner Switch At
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    refinerSwitchAt?: number;
    /**
     * Disable Extra Networks
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    disableExtraNetworks?: boolean;
    /**
     * Firstpass Image
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    firstpassImage?: string;
    /**
     * Comments
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    comments?: object;
    /**
     * Enable Hr
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    enableHr?: boolean;
    /**
     * Firstphase Width
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    firstphaseWidth?: number;
    /**
     * Firstphase Height
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    firstphaseHeight?: number;
    /**
     * Hr Scale
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrScale?: number;
    /**
     * Hr Upscaler
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrUpscaler?: string;
    /**
     * Hr Second Pass Steps
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrSecondPassSteps?: number;
    /**
     * Hr Resize X
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrResizeX?: number;
    /**
     * Hr Resize Y
     * @type {number}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrResizeY?: number;
    /**
     * Hr Checkpoint Name
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrCheckpointName?: string;
    /**
     * Hr Sampler Name
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrSamplerName?: string;
    /**
     * Hr Scheduler
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrScheduler?: string;
    /**
     * Hr Prompt
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrPrompt?: string;
    /**
     * Hr Negative Prompt
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    hrNegativePrompt?: string;
    /**
     * Force Task Id
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    forceTaskId?: string;
    /**
     * Sampler Index
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    samplerIndex?: string;
    /**
     * Script Name
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    scriptName?: string;
    /**
     * Script Args
     * @type {Array<string>}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    scriptArgs?: Array<string>;
    /**
     * Send Images
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    sendImages?: boolean;
    /**
     * Save Images
     * @type {boolean}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    saveImages?: boolean;
    /**
     * Alwayson Scripts
     * @type {object}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    alwaysonScripts?: object;
    /**
     * Infotext
     * @type {string}
     * @memberof StableDiffusionProcessingTxt2Img
     */
    infotext?: string;
}

export function StableDiffusionProcessingTxt2ImgFromJSON(json: any): StableDiffusionProcessingTxt2Img {
    return StableDiffusionProcessingTxt2ImgFromJSONTyped(json, false);
}

export function StableDiffusionProcessingTxt2ImgFromJSONTyped(json: any, ignoreDiscriminator: boolean): StableDiffusionProcessingTxt2Img {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'prompt': !exists(json, 'prompt') ? undefined : json['prompt'],
        'negativePrompt': !exists(json, 'negative_prompt') ? undefined : json['negative_prompt'],
        'styles': !exists(json, 'styles') ? undefined : json['styles'],
        'seed': !exists(json, 'seed') ? undefined : json['seed'],
        'subseed': !exists(json, 'subseed') ? undefined : json['subseed'],
        'subseedStrength': !exists(json, 'subseed_strength') ? undefined : json['subseed_strength'],
        'seedResizeFromH': !exists(json, 'seed_resize_from_h') ? undefined : json['seed_resize_from_h'],
        'seedResizeFromW': !exists(json, 'seed_resize_from_w') ? undefined : json['seed_resize_from_w'],
        'samplerName': !exists(json, 'sampler_name') ? undefined : json['sampler_name'],
        'scheduler': !exists(json, 'scheduler') ? undefined : json['scheduler'],
        'batchSize': !exists(json, 'batch_size') ? undefined : json['batch_size'],
        'nIter': !exists(json, 'n_iter') ? undefined : json['n_iter'],
        'steps': !exists(json, 'steps') ? undefined : json['steps'],
        'cfgScale': !exists(json, 'cfg_scale') ? undefined : json['cfg_scale'],
        'width': !exists(json, 'width') ? undefined : json['width'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'restoreFaces': !exists(json, 'restore_faces') ? undefined : json['restore_faces'],
        'tiling': !exists(json, 'tiling') ? undefined : json['tiling'],
        'doNotSaveSamples': !exists(json, 'do_not_save_samples') ? undefined : json['do_not_save_samples'],
        'doNotSaveGrid': !exists(json, 'do_not_save_grid') ? undefined : json['do_not_save_grid'],
        'eta': !exists(json, 'eta') ? undefined : json['eta'],
        'denoisingStrength': !exists(json, 'denoising_strength') ? undefined : json['denoising_strength'],
        'sMinUncond': !exists(json, 's_min_uncond') ? undefined : json['s_min_uncond'],
        'sChurn': !exists(json, 's_churn') ? undefined : json['s_churn'],
        'sTmax': !exists(json, 's_tmax') ? undefined : json['s_tmax'],
        'sTmin': !exists(json, 's_tmin') ? undefined : json['s_tmin'],
        'sNoise': !exists(json, 's_noise') ? undefined : json['s_noise'],
        'overrideSettings': !exists(json, 'override_settings') ? undefined : json['override_settings'],
        'overrideSettingsRestoreAfterwards': !exists(json, 'override_settings_restore_afterwards') ? undefined : json['override_settings_restore_afterwards'],
        'refinerCheckpoint': !exists(json, 'refiner_checkpoint') ? undefined : json['refiner_checkpoint'],
        'refinerSwitchAt': !exists(json, 'refiner_switch_at') ? undefined : json['refiner_switch_at'],
        'disableExtraNetworks': !exists(json, 'disable_extra_networks') ? undefined : json['disable_extra_networks'],
        'firstpassImage': !exists(json, 'firstpass_image') ? undefined : json['firstpass_image'],
        'comments': !exists(json, 'comments') ? undefined : json['comments'],
        'enableHr': !exists(json, 'enable_hr') ? undefined : json['enable_hr'],
        'firstphaseWidth': !exists(json, 'firstphase_width') ? undefined : json['firstphase_width'],
        'firstphaseHeight': !exists(json, 'firstphase_height') ? undefined : json['firstphase_height'],
        'hrScale': !exists(json, 'hr_scale') ? undefined : json['hr_scale'],
        'hrUpscaler': !exists(json, 'hr_upscaler') ? undefined : json['hr_upscaler'],
        'hrSecondPassSteps': !exists(json, 'hr_second_pass_steps') ? undefined : json['hr_second_pass_steps'],
        'hrResizeX': !exists(json, 'hr_resize_x') ? undefined : json['hr_resize_x'],
        'hrResizeY': !exists(json, 'hr_resize_y') ? undefined : json['hr_resize_y'],
        'hrCheckpointName': !exists(json, 'hr_checkpoint_name') ? undefined : json['hr_checkpoint_name'],
        'hrSamplerName': !exists(json, 'hr_sampler_name') ? undefined : json['hr_sampler_name'],
        'hrScheduler': !exists(json, 'hr_scheduler') ? undefined : json['hr_scheduler'],
        'hrPrompt': !exists(json, 'hr_prompt') ? undefined : json['hr_prompt'],
        'hrNegativePrompt': !exists(json, 'hr_negative_prompt') ? undefined : json['hr_negative_prompt'],
        'forceTaskId': !exists(json, 'force_task_id') ? undefined : json['force_task_id'],
        'samplerIndex': !exists(json, 'sampler_index') ? undefined : json['sampler_index'],
        'scriptName': !exists(json, 'script_name') ? undefined : json['script_name'],
        'scriptArgs': !exists(json, 'script_args') ? undefined : json['script_args'],
        'sendImages': !exists(json, 'send_images') ? undefined : json['send_images'],
        'saveImages': !exists(json, 'save_images') ? undefined : json['save_images'],
        'alwaysonScripts': !exists(json, 'alwayson_scripts') ? undefined : json['alwayson_scripts'],
        'infotext': !exists(json, 'infotext') ? undefined : json['infotext'],
    };
}

export function StableDiffusionProcessingTxt2ImgToJSON(value?: StableDiffusionProcessingTxt2Img | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'prompt': value.prompt,
        'negative_prompt': value.negativePrompt,
        'styles': value.styles,
        'seed': value.seed,
        'subseed': value.subseed,
        'subseed_strength': value.subseedStrength,
        'seed_resize_from_h': value.seedResizeFromH,
        'seed_resize_from_w': value.seedResizeFromW,
        'sampler_name': value.samplerName,
        'scheduler': value.scheduler,
        'batch_size': value.batchSize,
        'n_iter': value.nIter,
        'steps': value.steps,
        'cfg_scale': value.cfgScale,
        'width': value.width,
        'height': value.height,
        'restore_faces': value.restoreFaces,
        'tiling': value.tiling,
        'do_not_save_samples': value.doNotSaveSamples,
        'do_not_save_grid': value.doNotSaveGrid,
        'eta': value.eta,
        'denoising_strength': value.denoisingStrength,
        's_min_uncond': value.sMinUncond,
        's_churn': value.sChurn,
        's_tmax': value.sTmax,
        's_tmin': value.sTmin,
        's_noise': value.sNoise,
        'override_settings': value.overrideSettings,
        'override_settings_restore_afterwards': value.overrideSettingsRestoreAfterwards,
        'refiner_checkpoint': value.refinerCheckpoint,
        'refiner_switch_at': value.refinerSwitchAt,
        'disable_extra_networks': value.disableExtraNetworks,
        'firstpass_image': value.firstpassImage,
        'comments': value.comments,
        'enable_hr': value.enableHr,
        'firstphase_width': value.firstphaseWidth,
        'firstphase_height': value.firstphaseHeight,
        'hr_scale': value.hrScale,
        'hr_upscaler': value.hrUpscaler,
        'hr_second_pass_steps': value.hrSecondPassSteps,
        'hr_resize_x': value.hrResizeX,
        'hr_resize_y': value.hrResizeY,
        'hr_checkpoint_name': value.hrCheckpointName,
        'hr_sampler_name': value.hrSamplerName,
        'hr_scheduler': value.hrScheduler,
        'hr_prompt': value.hrPrompt,
        'hr_negative_prompt': value.hrNegativePrompt,
        'force_task_id': value.forceTaskId,
        'sampler_index': value.samplerIndex,
        'script_name': value.scriptName,
        'script_args': value.scriptArgs,
        'send_images': value.sendImages,
        'save_images': value.saveImages,
        'alwayson_scripts': value.alwaysonScripts,
        'infotext': value.infotext,
    };
}


