/* tslint:disable */
/* eslint-disable */
/**
 * sdapiv1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * UpscalerItem
 * @export
 * @interface UpscalerItem
 */
export interface UpscalerItem {
    /**
     * Name
     * @type {string}
     * @memberof UpscalerItem
     */
    name: string;
    /**
     * Model Name
     * @type {string}
     * @memberof UpscalerItem
     */
    modelName?: string;
    /**
     * Path
     * @type {string}
     * @memberof UpscalerItem
     */
    modelPath?: string;
    /**
     * URL
     * @type {string}
     * @memberof UpscalerItem
     */
    modelUrl?: string;
    /**
     * Scale
     * @type {number}
     * @memberof UpscalerItem
     */
    scale?: number;
}

export function UpscalerItemFromJSON(json: any): UpscalerItem {
    return UpscalerItemFromJSONTyped(json, false);
}

export function UpscalerItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpscalerItem {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'modelName': !exists(json, 'model_name') ? undefined : json['model_name'],
        'modelPath': !exists(json, 'model_path') ? undefined : json['model_path'],
        'modelUrl': !exists(json, 'model_url') ? undefined : json['model_url'],
        'scale': !exists(json, 'scale') ? undefined : json['scale'],
    };
}

export function UpscalerItemToJSON(value?: UpscalerItem | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'model_name': value.modelName,
        'model_path': value.modelPath,
        'model_url': value.modelUrl,
        'scale': value.scale,
    };
}


